language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=gcc GCC=5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=gcc GCC=6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libc++-dev
      env: COMPILER=clang CLANG=3.7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - libc++-dev
      env: COMPILER=clang CLANG=3.8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
            - libc++-dev
      env: COMPILER=clang CLANG=3.9
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: osx
      osx_image: xcode8
      compiler: clang
before_install:
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$COMPILER" == "gcc" ]]; then
          sudo apt-get install libtbb-dev;
          export CXX=g++-$GCC CC=gcc-$GCC;
        fi
        if [[ "$COMPILER" == "clang" ]]; then
          sudo apt-get install libtbb-dev;
          export CXX=clang++-$CLANG CC=clang-$CLANG;
          export CXXFLAGS="-stdlib=libc++";
        fi
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install tbb;
        export CXX=clang++ CC=clang;
      fi
install:
    - cmake -DDOWNLOAD_GTEST=ON .
    - make VERBOSE=1 -j2 test_zcode
    - cd test
script:
- ./test_zcode